### ISSUE TITLE
Scammer removed bot

### ISSUE THREAD

**Issue by MrHash** [PhABC/antiScamBot_slack#13]
A scammer has been able to remove the bot from the system. Please advise:
![screen shot 2017-08-30 at 12 33 26](https://user-images.githubusercontent.com/390925/29870470-8313aaaa-8d7f-11e7-980b-483f3ec4faed.png)

**Comment by PhABC** [comment]
Thanks for reporting!

It is imperative that you only allow team owners and admins to manage applications. You can go in the **Manage Applications* to set this up, if you are a Team Owner. Otherwise, request the team owner to set this up. 

Should look like this ; 

![image](https://user-images.githubusercontent.com/9306422/29871923-81a2c1f2-8d5b-11e7-9f7e-6157a54e8228.png)

**Comment by MrHash** [comment]
Ok will double check. Also I IP whitelisted the app to my Digital Ocean droplet. This is probably also a sensible security measure.

**Comment by PhABC** [comment]
That's a great idea as well.

**Comment by PhABC** [comment]
Was this solved @MrHash ?

**Comment by MrHash** [comment]
yes i think that solved it, thanks
